In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

def readFile(filename,w,v):
	f = open(filename, "r")
	i=0
	for line in f:
		if line[0]=="i":
			data = line.split()
			w[i]=int(data[1])
			for j in range(v.shape[1]):
				v[i,j]=int(data[2+j])
			i=i+1
		else:
			if line[0]=="W":
				data = line.split()	
				W=int(data[1])
	f.close()
	return W


def readPoints(filename,p):
	f = open(filename, "r")
	nbPND = 0
	for line in f:
		nbPND += 1
	YN = np.zeros((nbPND,p))
	f = open(filename, "r")
	i=0
	for line in f:
		data = line.split()
		for j in range(p):
			YN[i][j]=int(data[j])
		i=i+1
	f.close()
	return YN


In [16]:
w=np.zeros(200,dtype=int)
v=np.zeros((200,6),dtype=int)
filename = "data/2KP200-TA-0.dat"
W=readFile(filename,w,v)

#Génération de m solutions aléatoires
m=100

costs = {}
solutions = {}

for i in range(m):
	w_total = 0
	current_solution = set()
	current_cost =  np.zeros(v.shape[1])
	arr = np.arange(w.shape[0])
	np.random.shuffle(arr)
	for j in arr:
		if w_total + w[j] <= W:
			current_solution.add(j)
			next_item = v[j]
			w_total += w[j]
			for k in range(v.shape[1]):
				current_cost[k] += next_item[k]
	costs[i] = current_cost
	solutions[i] = current_solution

print(costs)
print(solutions)
print(w[np.array(list(solutions[0]))].sum())

51855
{0: array([56417., 51818., 51930., 52536., 49101., 56204.]), 1: array([57925., 52614., 52423., 53513., 50610., 53623.]), 2: array([58371., 52997., 54029., 55083., 50522., 51816.]), 3: array([49583., 47606., 46518., 46531., 43798., 48994.]), 4: array([56687., 51441., 49812., 48787., 47463., 51119.]), 5: array([53252., 48378., 52805., 49354., 51214., 48578.]), 6: array([57324., 53669., 57725., 54269., 48650., 52582.]), 7: array([55643., 54287., 56075., 50288., 49829., 50752.]), 8: array([55553., 52950., 54966., 50427., 50966., 53501.]), 9: array([60385., 51976., 52129., 54210., 50181., 53516.]), 10: array([53624., 49421., 50152., 49037., 49163., 51188.]), 11: array([63788., 58985., 60070., 56044., 55075., 57530.]), 12: array([52833., 50117., 51238., 51262., 47269., 50235.]), 13: array([49515., 48466., 52870., 48365., 48032., 48296.]), 14: array([58405., 53254., 54393., 49434., 47839., 49797.]), 15: array([51783., 53236., 48888., 50955., 49762., 49175.]), 16: array([57633., 47914., 

In [3]:
from pareto import *

#Une instance d'un dictionnaire de vecteurs de 6 coûts
dico = {2:np.array([1,2,3,4,2,3]),0:np.array([6,8,9,10,11,12]),1:np.array([4,5,1,4,2,3])}

#Une autre instance avec 10 vecteurs randoms de couts
dico2 = {i:np.random.randint(1,10,6) for i in range(10)}

print(pareto_front(dico))

print(dico2)
print(pareto_front(dico2))

{0: array([1, 2, 3, 4, 2, 8]), 1: array([4, 5, 1, 4, 2, 3]), 3: array([1, 4, 3, 4, 2, 3])}
{0: array([ 6,  8,  9, 10, 11, 12])}
{0: array([3, 2, 9, 3, 6, 4]), 1: array([3, 9, 6, 7, 6, 4]), 2: array([4, 2, 5, 1, 2, 9]), 3: array([2, 7, 1, 2, 9, 3]), 4: array([6, 5, 1, 5, 8, 9]), 5: array([8, 9, 3, 6, 8, 5]), 6: array([1, 2, 4, 2, 4, 3]), 7: array([3, 2, 9, 7, 6, 7]), 8: array([7, 3, 2, 6, 6, 6]), 9: array([2, 1, 5, 7, 8, 2])}
{1: array([3, 9, 6, 7, 6, 4]), 2: array([4, 2, 5, 1, 2, 9]), 3: array([2, 7, 1, 2, 9, 3]), 4: array([6, 5, 1, 5, 8, 9]), 5: array([8, 9, 3, 6, 8, 5]), 7: array([3, 2, 9, 7, 6, 7]), 8: array([7, 3, 2, 6, 6, 6]), 9: array([2, 1, 5, 7, 8, 2])}


In [4]:
#Retourne true si u domine v, false sinon
def pareto_dominance_maximisation(u, v):
    return np.all(u >= v) and np.any(u > v)

In [5]:
from ndtree import *

In [6]:
dico_test = {0: np.array([9, 1, 5, 9, 9, 1]), 1: np.array([1, 4, 8, 3, 2, 2]), 2: np.array([6, 5, 9, 6, 9, 9]), 3: np.array([1, 5, 1, 6, 3, 6]), 4: np.array([5, 9, 5, 2, 9, 2]), 5: np.array([6, 1, 9, 9, 7, 4]), 6: np.array([6, 8, 4, 8, 6, 2]), 7: np.array([3, 7, 9, 5, 3, 1]), 8: np.array([2, 4, 5, 8, 6, 7]), 9: np.array([7, 1, 6, 6, 4, 2])}
solutions_test = {0: [9,1], 1: [1,3], 2: [6,4], 3: [1,3], 4: [5,9], 5: [6,7], 6: [6,1], 7: [3,8], 8: [2,5], 9: [7,6]} #solution fictive pour le dico_test

#Test de l'insertion dans l'arbre
tree = NDTree(pareto_dom_func = pareto_dominance_maximisation)
for i in range(10):
    tree.update_tree(dico_test[i], solutions_test[i])
print(dico_test)
print(str(tree.root))
tree.update_tree(np.array([1, 1, 1, 1, 1, 1]), [1,1])
print(str(tree.root))
tree.update_tree(np.array([20, 9, 9, 9, 9, 9]), [9,1])
print(str(tree.root))

{0: array([9, 1, 5, 9, 9, 1]), 1: array([1, 4, 8, 3, 2, 2]), 2: array([6, 5, 9, 6, 9, 9]), 3: array([1, 5, 1, 6, 3, 6]), 4: array([5, 9, 5, 2, 9, 2]), 5: array([6, 1, 9, 9, 7, 4]), 6: array([6, 8, 4, 8, 6, 2]), 7: array([3, 7, 9, 5, 3, 1]), 8: array([2, 4, 5, 8, 6, 7]), 9: array([7, 1, 6, 6, 4, 2])}
{0: array([9, 1, 5, 9, 9, 1]), 7: array([2, 4, 5, 8, 6, 7]), 4: array([6, 1, 9, 9, 7, 4]), 2: array([6, 5, 9, 6, 9, 9]), 8: array([7, 1, 6, 6, 4, 2]), 3: array([5, 9, 5, 2, 9, 2]), 6: array([3, 7, 9, 5, 3, 1]), 5: array([6, 8, 4, 8, 6, 2])}
	{0: array([9, 1, 5, 9, 9, 1]), 7: array([2, 4, 5, 8, 6, 7]), 4: array([6, 1, 9, 9, 7, 4]), 2: array([6, 5, 9, 6, 9, 9]), 8: array([7, 1, 6, 6, 4, 2])}
	{3: array([5, 9, 5, 2, 9, 2]), 6: array([3, 7, 9, 5, 3, 1]), 5: array([6, 8, 4, 8, 6, 2])}

{0: array([9, 1, 5, 9, 9, 1]), 7: array([2, 4, 5, 8, 6, 7]), 4: array([6, 1, 9, 9, 7, 4]), 2: array([6, 5, 9, 6, 9, 9]), 8: array([7, 1, 6, 6, 4, 2]), 3: array([5, 9, 5, 2, 9, 2]), 6: array([3, 7, 9, 5, 3, 1]), 5:

In [17]:
#Donne les voisins de la solution sol, dont la valeur de la solution est cost, pour la liste d'objet obj et leur poids weight
def voisinage(cost, sol, obj, weight, max_weight):
    inside = np.array(list(sol))
    outside = np.delete(np.array(list(range(len(obj)))), inside)

    print(inside)
    print(outside)

    w_sol = w[np.array(list(sol))].sum()
    voisinage = []

print(v)
print(w)
voisinage(0, solutions[0], v, w, W)

[[783 840 906 823 623 631]
 [198 798 820 509 443 987]
 [278 335 100 429 269 709]
 ...
 [967 466 112 892 524 952]
 [780 184 900 889 667 540]
 [258 766 673 551 752 141]]
[394 911 768 477 513 636 607 138 401 998 839 637 972 527 891 807 949 193
 349 458 970 267 760 532 931 285 354 440 331 351 589 440 814 483 920 641
 281 447 276 170 126 984 383 294 245 126 745  53 240 656 759 520 205 573
 158 890  55   5 181 913 552 687 757 577 629 833 831 903 497 889 248 700
 232 224 971 719 592 337   4 833 483 712  41 674 185 730 203 653  88 686
 362 666 289 984 332 958 699 384 916 793 905 498 274 464 291 727 492 179
 122 325 622 496 659 152 647 332 934 659 158 518 426 245 639 897   6 294
 721 986 474 100 657  52 781 119 530 304 170 619 829 923 226 357 815 258
 836 198 674 201 434 533  15 306 650 686 312 533 643 362 678  64 619   2
 262 181 879 885 503 904 706 739 926 494 799 657 325 638 795 471 865 413
 645 579 518 113  49 638 413  18 813 477  75 223 923 439 948 334 478 884
 458 904]
[9 1]
[  0   2   3 